apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-api-pvc
  namespace: flaskapi
spec:
  storageClassName: managed-csi
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi