# apiVersion: v1
# kind: Secret
# metadata:
#   name: cloudflare-key1
#   namespace: istio-system
# type: Opaque
# stringData:
#   api-key: 23aef12c1f2a3244e13bfc3dceff911ba37e4

# apiVersion: cert-manager.io/v1
# kind: Issuer
# metadata:
#   name: cloudflare-prod1
#   namespace: istio-system
# spec:
#   acme:
#     server: https://acme-v02.api.letsencrypt.org/directory
#     email: nwajienelson@gmail.com
#     privateKeySecretRef:
#       name: cloudflare-prod1
#     solvers:
#     - selector:
#         dnsNames:
#         - netroxlabs.com
#       dns01:
#         cloudflare:
#           email: nwajienelson@gmail.com
#           apiKeySecretRef:
#             name: cloudflare-key1  <--- reference the key from the secret created above
#             key: api-key

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cloudflare-cert
  namespace: istio-system
spec:
  secretName: cloudflare-tls
  issuerRef:
    name: cloudflare-prod1
    kind: Issuer
  dnsNames:
  - netroxlabs.com