# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: netroxtechnologies-prod
#   namespace: istio-system
# spec:
#   secretName: netroxtechnologies-tls
#   issuerRef:
#     name: letsencrypt-prod
#     kind: ClusterIssuer
#   dnsNames:
#   - netroxtechnologies.com

# ---


apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kube-prod-aws
  namespace: istio-system
spec:
  secretName: kube-tls
  issuerRef:
    name: aws-prod
    kind: Issuer
  dnsNames:
  - kube-test.link